id: ab2bc92539684f72a765ceda84ed4950
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_1-1-The_Chapter_on_Going_Forth-v1
  language: bo
  author: ''
  volume: {}
